//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class TKYSEntities : DbContext
{
    public TKYSEntities()
        : base("name=TKYSEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<bildirim> bildirim { get; set; }
    public virtual DbSet<borc> borc { get; set; }
    public virtual DbSet<daire> daire { get; set; }
    public virtual DbSet<etkinlik> etkinlik { get; set; }
    public virtual DbSet<gelir> gelir { get; set; }
    public virtual DbSet<gider> gider { get; set; }
    public virtual DbSet<@is> @is { get; set; }
    public virtual DbSet<is_turu> is_turu { get; set; }
    public virtual DbSet<kullanici> kullanici { get; set; }
    public virtual DbSet<rezervasyon> rezervasyon { get; set; }
    public virtual DbSet<sosyal_tesis> sosyal_tesis { get; set; }
}
