

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class bildirim
{

    public int id { get; set; }

    public string detay { get; set; }

    public string ad { get; set; }

    public Nullable<int> kullanici_id { get; set; }



    public virtual kullanici kullanici { get; set; }

}


public partial class borc
{

    public int id { get; set; }

    public string ad { get; set; }

    public Nullable<int> miktar { get; set; }

    public Nullable<int> kullanici_id { get; set; }



    public virtual kullanici kullanici { get; set; }

}


public partial class daire
{

    public int id { get; set; }

    public string blok { get; set; }

    public int kat { get; set; }

    public int daire_no { get; set; }

    public int daire_genisligi { get; set; }

    public Nullable<int> kullanici_id { get; set; }



    public virtual kullanici kullanici { get; set; }

}


public partial class etkinlik
{

    public int id { get; set; }

    public string ad { get; set; }

    public string detay { get; set; }

    public System.DateTime tarih { get; set; }

    public Nullable<int> kullanici_id { get; set; }



    public virtual kullanici kullanici { get; set; }

}


public partial class gelir
{

    public int id { get; set; }

    public string ad { get; set; }

    public Nullable<int> miktar { get; set; }

}


public partial class gider
{

    public int id { get; set; }

    public string ad { get; set; }

    public Nullable<int> miktar { get; set; }

}


public partial class @is
{

    public int id { get; set; }

    public string ad { get; set; }

    public string detay { get; set; }

    public Nullable<int> is_turu { get; set; }



    public virtual is_turu is_turu1 { get; set; }

}


public partial class is_turu
{

    public is_turu()
    {

        this.@is = new HashSet<@is>();

    }


    public int id { get; set; }

    public string ad { get; set; }



    public virtual ICollection<@is> @is { get; set; }

}


public partial class kullanici
{

    public kullanici()
    {

        this.bildirim = new HashSet<bildirim>();

        this.borc = new HashSet<borc>();

        this.daire = new HashSet<daire>();

        this.etkinlik = new HashSet<etkinlik>();

        this.rezervasyon = new HashSet<rezervasyon>();

    }


    public int id { get; set; }

    public string ad { get; set; }

    public string soyad { get; set; }

    public bool cinsiyet { get; set; }

    public string cep_telefonu { get; set; }

    public string e_posta { get; set; }

    public string kullanici_adi { get; set; }

    public string sifre { get; set; }

    public string yetki { get; set; }



    public virtual ICollection<bildirim> bildirim { get; set; }

    public virtual ICollection<borc> borc { get; set; }

    public virtual ICollection<daire> daire { get; set; }

    public virtual ICollection<etkinlik> etkinlik { get; set; }

    public virtual ICollection<rezervasyon> rezervasyon { get; set; }

}


public partial class rezervasyon
{

    public int id { get; set; }

    public string ad { get; set; }

    public string detay { get; set; }

    public Nullable<int> sosyal_tesis_id { get; set; }

    public Nullable<int> kullanici_id { get; set; }



    public virtual kullanici kullanici { get; set; }

    public virtual sosyal_tesis sosyal_tesis { get; set; }

}


public partial class sosyal_tesis
{

    public sosyal_tesis()
    {

        this.rezervasyon = new HashSet<rezervasyon>();

    }


    public int id { get; set; }

    public string ad { get; set; }

    public Nullable<int> kapasite { get; set; }



    public virtual ICollection<rezervasyon> rezervasyon { get; set; }

}

